# Save as .codeclimate.yml (note leading .) in project root directory
version: "2"
languages:
  Ruby: false
  JavaScript: true
  PHP: false
checks:
  file-lines:
    config:
      threshold: 500
  method-lines:
    config:
      threshold: 75
  method-complexity:
    config:
      threshold: 10
  similar-code:
    config:
      threshold: 65
plugins:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 110
          count_threshold: 3
exclude_paths:
- "public/vendor/*"
- "test/*"