name: Run flow typechecking

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  npx-standard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run flow
        run: npm run flow check -all
