name: Fly Deploy
on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main


jobs:
  deploy:
    name: Deploy app
    services:
      redis:
        image: 'redis:2.8.23'
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
      # - run: |
      #     echo "$MY_SECRET" >> config.ini
      #     cat config.ini
        env:
          # MY_SECRET: ${{ secrets.KEY }}
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}